permissions:
  contents: write
  
name: build

on:
  pull_request:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-latest]
        lazarus-versions: [dist]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install Lazarus
        uses: gcarreno/setup-lazarus@v3
        with:
          lazarus-version: ${{ matrix.lazarus-versions }}
          include-packages: ""
          with-cache: true
      - name: Build the Main Application
        if: ${{ matrix.operating-system != 'macos-latest' }}
        run: lazbuild -B "caffeinator.lpi"
      - name: Build the Main Application (macOS)
        if: ${{ matrix.operating-system == 'macos-latest' }}
        run: lazbuild -B --ws=cocoa "caffeinator.lpi"
      - name: Get short commit SHA
        shell: bash
        run: |
          echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
      - name: Debug Show SHORT_SHA
        run: echo "SHORT_SHA is $SHORT_SHA"
      - name: Upload caffeinator.exe with short SHA
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: caffeinator.exe
          asset_name: caffeinator.exe
          tag: caffeinator-release-${{ env.SHORT_SHA }}
          overwrite: true
          body: "Release for commit ${{ env.SHORT_SHA }}"
